services:
  - type: web
    name: paradokstreetwear
    runtime: node
    buildCommand: npm install && node seed.js
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
